# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_auto_20170209_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('like', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e')),
                ('release_time', models.DateField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_of_author_set', related_query_name='commentOfAuthor', to='User.User', verbose_name='\u4f5c\u8005')),
            ],
            options={
                'ordering': ['-release_time'],
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('like', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e')),
                ('release_time', models.DateField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_of_author_set', related_query_name='postingOfAuthor', to='User.User', verbose_name='\u4f5c\u8005')),
            ],
            options={
                'ordering': ['-release_time'],
                'verbose_name': '\u5e16\u5b50',
                'verbose_name_plural': '\u5e16\u5b50',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='\u6807\u9898', max_length=250, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('release_time', models.DateField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_of_author_set', related_query_name='topicOfAuthor', to='User.User', verbose_name='\u4f5c\u8005')),
            ],
            options={
                'ordering': ['-release_time'],
                'verbose_name': '\u8bdd\u9898',
                'verbose_name_plural': '\u8bdd\u9898',
            },
        ),
        migrations.AddField(
            model_name='posting',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_of_topic_set', related_query_name='postingOfTopic', to='Forum.Topic', verbose_name='\u4e3b\u9898'),
        ),
        migrations.AddField(
            model_name='comment',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_of_posting_set', related_query_name='commentOfPosting', to='Forum.Posting', verbose_name='\u5e16\u5b50'),
        ),
    ]
