# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_auto_20170209_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='', verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='content',
            field=models.TextField(default='', verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(default='', verbose_name='\u5185\u5bb9'),
        ),
    ]
