# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20170212_1425'),
        ('Forum', '0003_auto_20170209_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(related_name='comment_like_of_user', related_query_name='likeOfComment', to='User.User', verbose_name='\u70b9\u8d5e'),
        ),
        migrations.RemoveField(
            model_name='posting',
            name='like',
        ),
        migrations.AddField(
            model_name='posting',
            name='like',
            field=models.ManyToManyField(related_name='posting_like_of_user', related_query_name='likeOfPosting', to='User.User', verbose_name='\u70b9\u8d5e'),
        ),
    ]
