# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=200, verbose_name='\u7528\u6237\u540d')),
                ('real_name', models.CharField(default='', max_length=200, verbose_name='\u771f\u540d')),
                ('password', models.CharField(blank=True, default=b'e10adc3949ba59abbe56e057f20f883e', max_length=200, verbose_name='\u5bc6\u7801')),
                ('sign', models.CharField(default='', max_length=200, verbose_name='\u4e2a\u6027\u7b7e\u540d')),
                ('avatar', models.ImageField(default='avatars/default.jpg', upload_to='avatars/')),
            ],
            options={
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
    ]
