# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 06:25
from __future__ import unicode_literals

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20170209_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to=User.models.upload_avatar),
        ),
    ]
