# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0004_auto_20170210_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='state',
            new_name='is_over',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='title',
            new_name='name',
        ),
    ]
