# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0005_auto_20170211_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_of_course_set', related_query_name='homeworkOfCourse', to='Homework.Course', verbose_name='\u8bfe\u7a0b'),
        ),
    ]
