# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0006_auto_20170212_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='finished_number',
            field=models.IntegerField(default=0, verbose_name='\u63d0\u4ea4\u4eba\u6570'),
        ),
    ]
